apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
      - name: udacity-capstone-app
        image: topriddy/udacity-capstone-app
        ports:
        - containerPort: 8080